title: 'BitDevsKLA'
tagline: 'BitDevsKLA is a monthly meetup devoted to the research and development of Bitcoin'

menu:
  - {name: 'Events', url: '/events.html'}
  - {name: 'Luma', url: 'https://lu.ma/bitdevskla', external: true}
  - {name: 'Discord', url: 'https://discord.gg/jxdvET2PdS', external: true}
  - {name: 'X', url: 'https://x.com/BitDevsKLA', external: true}
  - {name: 'WhatsApp', url: 'https://chat.whatsapp.com/FohaYjTdSMCIYaqACzoVQs', external: true}
